# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Our Adventure Baby
email: clay.schick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Our adventure living and traveling in a motorhome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ouradventurebaby.com" # the base hostname & protocol for your site
#url: "http://localhost:4000" 
twitter_username: brandyfine
github_username:  brandyfine

highlighter: null

paginate_path: "blog/page:num/"
gems: [jekyll-paginate]
paginate: 2

# Build settings
markdown: kramdown
